### ISSUE TITLE
Overload of requests leading to "Awaiting request from Farcaster protocol hubs..."

### ISSUE THREAD

**Issue by web3Gurung** [dylsteck/casterscan#5]
While loading the website, it isn't able to parse live feed from farcaster.

![image](https://github.com/dylsteck/casterscan/assets/72032538/9f6391ad-d104-4dd4-a0d7-428ed7c6300e)
![image](https://github.com/dylsteck/casterscan/assets/72032538/99092eb6-90f4-4526-9f47-35c06791678f)

**Comment by dylsteck** [comment]
Closing because the database is back up as of last night, but thanks again for this!

**Comment by web3Gurung** [comment]
Looks good!
